# Modes: 1) depth, 2) single_rgb, 3) multi_rgb
train_mode: "single_rgb"
test_mode: "single_rgb"

# Test types: inference (to run inference.py); train (to monitor the training in train.py)
test_type: "inferenxe"
